# Generated by Django 5.0.6 on 2024-06-22 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_guests',
        ),
        migrations.AddField(
            model_name='reservation',
            name='party_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
