# Generated by Django 5.0.6 on 2024-06-23 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_reservation_date_and_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='party_size',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
